version: '3'
services:
  webserver:
    image: your_id/myserver
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 30s
      timeout: 10s
      retries: 3

  clidownload:
    image: appropriate/curl
    depends_on:
      webserver:
        condition: service_healthy
    entrypoint: sh -c "curl -s http://webserver:8080"